---
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: dev
  name: testing-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: slow
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /opt/Dev/deploy-src/address/testing-suriya/fepaxeladdress/paxeladdress
    server: 128.140.108.46
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
   namespace: dev
   name: testing-pv-claim
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: slow
  resources:
    requests:
      storage: 1Gi
